### ISSUE TITLE
Custom css-in-js solutions

### ISSUE THREAD

**Issue by degroote22** [alidcastano/rogue.js#14]
How would it be like to write custom plugins for rogue?
I'd like to support JSS to use Material-UI and it seems that only rogue-made hocs would work.
As I could see from their code, the hocs are simple and I could implement another one myself.
My question is: would that work? Because from what I could see from the docs it wouldn't.

Thanks for the awesome work!

**Comment by alidcastano** [comment]
So there are two ways to configure SSR support.

If the implementation doesn't require access to the `document` itself (e.g. to inject script tags) then you can do it via a hoc's/providers `getInitialProps` method. This is how the Rogue's Apollo and Redux hocs do it, and you can implement your own custom solution if the requirement is the same

The second way is by creating your own `server.js` file. I still have to document this but Rogue checks your root and '/src` directories for one, and if you don't have one, we use our own template (https://github.com/alidcastano/rogue/blob/master/src/templates/server.js).

In you need the second approach, then you'd just be using Rouge for its `renderApp` and `renderHtml` methods (the less code you have to maintain the better), and for the development experience (`npm run dev`, `npm run build`, etc.)

I'm open to any suggestions you may have!

**Comment by alidcastano** [comment]
Looks like Material UI inlines the css next to the top most component (https://material-ui.com/guides/server-rendering/#server-rendering) so this can maybe be done via a `hoc`

I'm also Thinking about whether we can use Helmet to inject document tags inside a `hoc` so that a custom `server.js` file wouldn't need to be used at all; will have to experiment with this when I get a chance

**Comment by alidcastano** [comment]
Good news

Rogue now makes it easier to configure SSR support for plugins/providers without having to bloat your `server.js` file

Check out the new documentation: https://github.com/alidcastano/rogue.js/tree/master/packages/rogue-app#custom-enhancements

It discusses methods to add tags to head or body of document (as is needed for material UI)

Btw, once you get it working, I'd be great to have PR and include it in examples for others!
