### ISSUE TITLE
Uncaught Error: Cannot find module 'core-js/modules/es6.typed.array-buffer'

### ISSUE THREAD

**Issue by vstepanyuk** [alidcastano/rogue.js#16]
bundle.js:39 Uncaught Error: Cannot find module 'core-js/modules/es6.typed.array-buffer'
    at newRequire (VM152 bundle.js:39)
    at localRequire (VM152 bundle.js:54)
    at Object.parcelRequire.1 (VM152 bundle.js:109)
    at newRequire (VM152 bundle.js:48)
    at parcelRequire.1 (VM152 bundle.js:80)
    at VM152 bundle.js:106

**Comment by alexparish** [comment]
I am also seeing this with Rogue 0.1.6.

The only code I have in my project is a file at src/App.js with the following contents:

```
import React from "react";

export default function App() {
  return <div>Hello World!</div>;
}

```

**Comment by alidcastano** [comment]
The `hello-world` example works for me, so that's likely caused by different dev environments 

I purposefully wrote Rogue code in boring old javascript and without JSX so it wouldn't need compiling but just realized I'm using recent node version (10.5.0) and not sure when `async/await` was introduced

Can you try doing this

```
npm install --save-dev babel-preset-env
```
And then add this to your .babelrc
```
{
    "presets": [
        [
            "env"
        ]
    ]
}
```

If this fixes issue then I'll just remove async/await statements (and any other es5+ statements) from Rogue scripts/bundle

**Comment by alexparish** [comment]
Upgrading to the recently published `rogue@0.2.4` fixed the problem for me. 

I didn't need to upgrade Node from 8 to 10 or add the `.babelrc` as you suggested above.

@vstepanyuk Is your problem resolved when updating to `rogue@0.2.4`? If so, this issue can be closed.

**Comment by alexparish** [comment]
Although the dev script works for me now, when I run `yarn run start` I see the following error:

```js
Error: Cannot find module '../scripts/start'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/Users/alex/Projects/rogue-test/node_modules/rogue/bin/rogue:14:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
```

**Comment by alidcastano** [comment]
Oh okay even better! Thanks for letting me know

And haha yea sorry, that command doesn't exist yet :) I'm porting my app over and fixing things along the way. I'll soon push it to production and will add add start script

**Comment by alexparish** [comment]
No worries! This project is absolutely awesome... I'm just impatient to play with it :)

As a heads up HMR seems to be broken in `0.2.4`.

**Comment by alidcastano** [comment]
Sometimes I have to run the save command a few times for it to work. Can you try that?

This is likely related to #11. Parcel adds a process variable to the client bundle on watch mode which caused client-side errors; so to get around that temporarily I'm rebuilding client when server bundle changes, which is likely why it feels a bit broken

**Comment by alexparish** [comment]
@vstepanyuk Damn. It would be worth letting @alidcastano know what environment you’re using and the steps you’re taking so he can try recreate it?

**Comment by alidcastano** [comment]
Yes, this works for me and @alexparish so it has to be an environment specific error, and I can resolve that without any information about your setup
