### ISSUE TITLE
add more examples

### ISSUE THREAD

**Issue by alidcastano** [alidcastano/rogue.js#19]
nextjs `/examples` folder provides a great starting point if anyone wants to help with this

Though I'm thinking so many examples aren't needed since Rogue is much simpler (It's basically just React and React Router 4!).

I'll soon create a starter template and I think that will be much more useful than examples; but I'll still leave this issue here in case anyone encounters it and wants to contribute/discuss

**Comment by jangerhofer** [comment]
From #13, I presume you want to swap the *default* `server.js` file to use Connect in order to slim down the dependencies of a starter project, and in #14 you allude to using Rogue programatically.  Would you, @alidcastano, consider it helpful to have a few examples of custom servers which use Rogue a la [Next.js](https://nextjs.org/docs/#custom-server-and-routing), e.g. with Hapi, Koa, etc.?

**Comment by alidcastano** [comment]
Sure, examples are always helpful

I'll be making the above change soon and adding documentation for it so porting over those examples for Nextjs or Nuxtjs shouldn't be difficult for anyone that wants to contribute

**Comment by ans-4175** [comment]
Hey, I'd like to learn use rogue.
Maybe while in my exploring I'm keen to add examples.
Any guideline how to contribute?

**Comment by alidcastano** [comment]
Hi @ans-4175 

Ideally learning Rogue shouldn't be too difficult since it's just React, React Router 4, and the server rendering of 'getInitialProps' 

But one way you can learn would be to first scan `roguejs/app` docs and then try porting over an example from Nextjs to Rogue

I'll note that this is a newer framework, so you might run into a few bombs along the way. Feel free to open issue / ask questions if so

**Comment by alidcastano** [comment]
Going to close this but know that examples are always welcome, specially now that API is stabilizing (just released v0.6.0 with some final breaking changes)
