### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by vstepanyuk** [alidcastano/rogue.js#20]
Sometimes bundle.js contains src/App.js

**Comment by alidcastano** [comment]
I'm pretty sure this is related to #16 (which I've reopened). When there's an error with the client bundle, you'll often get this `Uncaught SyntaxError: Unexpected token <` error.

**Comment by Cosmicist** [comment]
:thinking: not sure it's related to that one, I'm testing rogue (looking awesome btw!) and it seems to be that the bundle is being included like this: `<script src="bundle.js" defer=""></script>` so when you are in `/` it loads ok, but if you are in, say `/foo`, then it will try to load `/foo/bundle.js` which will actualy be the server rendered component that handles `/foo` uri.
