### ISSUE TITLE
Access parsed route parameters in getInitialProps

### ISSUE THREAD

**Issue by Cosmicist** [alidcastano/rogue.js#22]
It would be very useful to be able to access the parsed route params in `getInitialProps` to load a particular resource using the url params as identifiers.

For example, when navigating to `/users/:name`:

```javascript
export default class App extends React.Component {
  static async getInitialProps({ params }) {
    const user = await fetchUserByName(params.name)
    return { user }
  }
  // ...
}
```

I couldn't find a way to do this without parsing `req.url` manually.

**Comment by alidcastano** [comment]
Yes, this should definitely be an option

I'll likely add it while doing #13

**Comment by Cosmicist** [comment]
Awesome! I'm really loving Rogue so far, I'm still fairly new to the React world, and this sure make it a pleasure to work with. Keep up the great work!

**Comment by alidcastano** [comment]
Added in `@roguejs@0.4.2`; here are docs https://github.com/alidcastano/rogue.js/tree/master/packages/rogue-app#getinitialprops-ctx--data--void
