### ISSUE TITLE
Adopt Prettier / Eslint?

### ISSUE THREAD

**Issue by alexparish** [alidcastano/rogue.js#28]
What do you think about using [prettier](https://github.com/prettier/prettier) @alidcastano ?

Seems a good way of avoiding debates about code style.

**Comment by alidcastano** [comment]
Yea this would be great

I'd interested in help with any way to standardize the module e.g. adopting prettier, setting up continuous integration, etc. I personally suck at these things

**Comment by alexparish** [comment]
Great! I'll create a pull request to add prettier when I get a chance.

**Comment by alexparish** [comment]
I could add eslint at the same time if you like? Any preference on which eslint config to use? I'd normally go for https://github.com/airbnb/javascript.

**Comment by alidcastano** [comment]
Sure, I'm for any standardization that doesn't add a build step

**Comment by alexparish** [comment]
Do you have a Node version in mind for rogue? A minimum version of Node that users should have installed?

This will help guide the changes I can make when tweaking the code to make the linter happy.

**Comment by alexparish** [comment]
Scratch that... I see you're running the server code through Parcel (with babel-present-env) so we can use all the latest and greatest ES2015 and ESM goodness.

**Comment by alidcastano** [comment]
No, the .babelrc is for Jest so we can use jsx inside the tests

**Comment by alidcastano** [comment]
ideally lets do whatever node version supports async/await and arrow syntax if it's not too high 

maybe 

```
	"engines": {
		"node": ">=8.0.0",
		"npm": ">=5.0.0"
	},
```

**Comment by alidcastano** [comment]
having to compile would be a pain (#2) since parcel doesn't yet have it figured out for linked modules (https://github.com/parcel-bundler/parcel/issues/1617)

**Comment by alexparish** [comment]
Ah now I see why you are using `require` everywhere. I'll stick with that for now.

**Comment by ctrlplusb** [comment]
Nice move @alexparish. If you do go for `eslint-config-airbnb`, ensure you add the `eslint-config-prettier` underneath it to avoid style rule conflicts. You may already have intended on doing so, but thought it worth a shout out just in case you weren't familiar with it. 👍

**Comment by alidcastano** [comment]
eslint isn't option anymore since Rogue now uses typescript, anyone interested in this please up new issue for tslint
