### ISSUE TITLE
Feature: document/add support for mounting in an express app

### ISSUE THREAD

**Issue by dbkaplun** [alidcastano/rogue.js#41]
It would be great if Rogue could be used as part of a larger Express app. Thanks for considering!

**Comment by alidcastano** [comment]
Documentation has been added https://github.com/alidcastano/rogue.js/tree/master/packages/rogue-app#custom-server

I don't have time to add examples for every use-case myself but feel free to open new issue if you run into any problems. 

If you need a complete example to get started, I'd use the Nextjs/Nuxtjs repo examples as starting 
points
