### ISSUE TITLE
Implement with Create-react-app?

### ISSUE THREAD

**Issue by AlejandroMataGuillen** [alidcastano/rogue.js#64]
An example of how to add rogue to a default create-react-app would be great

**Comment by alidcastano** [comment]
This would be great, didnt think of of it as a possiblility since create-react-app recommends nextjs or razzle in their README

Is there an example project of people doing server rendering themselves with create react appp?

**Comment by AlejandroMataGuillen** [comment]
I don't know to be honest, but defitinely would be great to have another alternative to do ssr with create react app or maybe integrate with a current project with a differente structure

**Comment by alidcastano** [comment]
I think the with-spectrum does server-rendering and they use create-react-app: https://github.com/withspectrum/spectrum/

maybe they have some advice to give on this? cc @brianlovin @mxstbr or @uberbryn

**Comment by brianlovin** [comment]
@mxstbr could weigh in most tactfully here, but https://github.com/withspectrum/spectrum/tree/alpha/hyperion is our SSR worker if you want to poke around :)

**Comment by alidcastano** [comment]
Hey @brianlovin, thanks for the link! I'll take a look when I get a chance

Are you guys finding the experience pleasant? Any pain-points people should know about? (i.e. After using create-react-app for this, would you recommend it or point people towards other solutions like Razzle)

**Comment by antonybudianto** [comment]
Hi,

I created https://github.com/antonybudianto/cra-universal, it's a zero config and no eject for create-react-app.

**Comment by alidcastano** [comment]
was looking into this yesterday but it doesn't seem like create-react-app would be an ideal solution

looking at spectrum's setup (mentioned above), they use two different build setups for this (create-react-app and backpack) and while it seems to work for them (I wonder if they experience any problems with hmr, or do they just run SPA mode in dev?), I would be hesitant to start a project with it given that other options are available. Plus create-react-app repo says it's not recommended for ssr and backpack repo says it doesn't recommend using it for React ssr

**Comment by mxstbr** [comment]
> do they just run SPA mode in dev

This is what I do!
