### ISSUE TITLE
Odd behavior running with-razzle example

### ISSUE THREAD

**Issue by corydeppen** [alidcastano/rogue.js#67]
I'm running into very odd behavior using the with-razzle example. The Razzle app runs and reloads as expected prior to adding Rogue and I'm wondering if anyone else is seeing this behavior or not.

Steps to reproduce:

- Create new Razzle app

  `create-razzle-app with-razzle`
  `cd with-razzle`

- Start the app, make a change to `Home.js`, then verify the app is built and reloads as expected
- Install Rogue using specific version to match with-razzle example

  `yarn add @roguejs/app@0.6.9`

- Overwrite contents of local `server.js`, `index.js`, `client.js`, and `App.js` files with content from [with-razzle example directory](https://github.com/alidcastano/rogue.js/tree/master/examples/with-razzle) files
- Start the app, make a change to `App.js`, then verify the app is built and reloads as expected

  ```bash
  √ success server compiled in 141ms
  √ success client compiled in 165ms
  🔁  HMR Reloading `./server`...
  [HMR] Updated modules:
  [HMR]  - ./src/App.js
  [HMR]  - ./src/server.js
  [HMR] Update applied.
  √ success client compiled in 564ms
  ```

- Error displayed in the console:

  `Warning: Text content did not match. Server: "Roguejs with Razzle" Client: "Roguejs with Razzle!"`

- Browser still shows old content, but view source and JS bundle show the updated content
- Upgrade @rogue/app to 0.6.11
- Start the app, make a change to `App.js`, then verify the app is built and reloads as expected

  ```bash
  √ success server compiled in 750ms
  √ success client compiled in 671ms
  🔁  HMR Reloading `./server`...
  [HMR] Updated modules:
  [HMR]  - ./src/App.js
  [HMR]  - ./src/server.js
  [HMR] Update applied.
  √ success client compiled in 933ms
  ```

- Browser shows the change quickly, then reverts to the content as it was prior to the change. Also, the 'text content did not match' message is back in the console.
- View page source and JS bundle both have content matching the source

  ```json
  "dependencies": {
    "@roguejs/app": "0.6.11",
    "express": "4.16.3",
    "razzle": "2.2.0",
    "react": "16.4.1",
    "react-dom": "16.4.1",
    "react-router-dom": "4.3.1"
  }
  ```

OS: Windows 10
Node: 8.11.3
Yarn: 1.5.1

**Comment by alidcastano** [comment]
I was running into this error with previous version of Rogue but I thought I had fixed this

can you link me to the exact repo you're experimenting with Rogue on? (since it's not the with-razzle example and that example does work for me at least)

**Comment by alidcastano** [comment]
hi @stevefan1999 thanks for commenting 

I haven't been able to look into this yet but what code did you have to add to fix the problem?

**Comment by stevefan1999** [comment]
@alidcastano 🤔Just some standard react-hot-loader stuff, either add a `hot(module)` decorator or put `if (module.hot) module.hot.accept()` on the last line of your `client.js`.

**Comment by alidcastano** [comment]
@corydeppen looks like this might be specific to razzle and react-hot-loader

Can you try above and see if it fixes your problem 

Otherwise I'll give it a look when I get a chance

**Comment by corydeppen** [comment]
To be clear, the Razzle project reloads as expected prior to adding Rogue.

Adding react-hot-loader on top of Razzle doesn't seem appropriate, since Razzle already [sets up HMR](https://github.com/jaredpalmer/razzle/blob/master/packages/razzle-dev-utils/webpackHotDevClient.js) for you. Further, [`index.js`](https://github.com/corydeppen/rogue-with-razzle/blob/master/src/index.js#L16-L26) in my example project calls `module.hot.accept`.

**Comment by alidcastano** [comment]
@corydeppen looking into this now but btw just realized the after.js example (https://github.com/jaredpalmer/razzle/blob/master/examples/with-afterjs/src/client.js#L17) also includes the line @stevefan1999 mentioned, so that's likely the issue

**Comment by alidcastano** [comment]
@corydeppen I forked your example and can confirm that added the above snippet + upgrading to 0.7.0 fixes the problem (at least on my side) 

Also updated with-razzle example so others don't run into this issue
